version: '3.8'
services:
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: es01
        environment:
            - node.name=es01
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
        volumes:
            - type: volume
              source: data01
              target: /usr/share/elasticsearch/data
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - elk
        
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.0
        container_name: kibana01
        environment:
            ELASTICSEARCH_HOSTS: http://es01:9200
        networks:
            - elk
        ports:
            - "5601:5601"
        depends_on:
            - es01

    logstash:
        build:
            context: ./
        image: logstash01
        container_name: logstash01
        volumes:
            - type: bind
              source: ./pipeline
              target: /usr/share/logstash/pipeline
        ports:
            - "9600:9600"
            - "5044:5044"
            - "5000:5000"
        environment:
            
            LS_JAVA_OPTS: "-Xms512m -Xmx512m"
        networks:
            - elk
        depends_on:
            - es01
              
networks:
  elk:
    driver: bridge

volumes:
  data01:
    driver: local
